### ISSUE TITLE
Build Error with CLT 8.0

### ISSUE THREAD

**Issue by FranciscoAmado** [intercom/intercom-ios#150]
Hi guys,

I've noticed that the framework doesn't build one's using the Command Line Tools of Xcode 8.0

## Version info
  - Intercom for iOS version: 3.0.3
  - iOS version: 8.0
  - Xcode version: 8.0

## Expected behavior

Carthage fetches intercom and builds the framework

## Actual behavior

Fetch is made correctly, build is skipped 

## Steps to reproduce
 1. Change CLT to Xcode 8.0
 2. Carthage Update
 3. Check Carthage/Build/iOS, no .framework is created there

## Logs

![screen shot 2016-07-26 at 18 55 55](https://cloud.githubusercontent.com/assets/6344795/17149357/dd3394e4-5362-11e6-83b3-5f32eb003178.png)

Thanks in advance,
Francisco

**Comment by jtreanor** [comment]
Hi @FranciscoAmado,

It appears there is an issue with the latest version of Carthage (https://github.com/Carthage/Carthage/pull/1386) that may have led to the archive being built incorrectly.

I have updated the archive for 3.0.3. Can you try run `carthage update` once more to see if the issue is now resolved?

**Comment by FranciscoAmado** [comment]
Hi @jtreanor,

Thank you! `carthage update` worked and it managed to build the .framework.
After adding the framework to the **Linked Frameworks** and the .framework path to the **Copy Carthage Frameworks** Build phase I'm having problems build the entire project.
`Found an unexpected Mach-O header code: 0x72613c21`

I'll be also checking in the Carthage repo for something similar to this.

Thank you once again,
Francisco

**Comment by jtreanor** [comment]
@FranciscoAmado great, I'm glad this is resolved for you.

I believe the error you are seeing is caused by accidentally copying the framework into your apps resources. A solution is [here](http://stackoverflow.com/questions/26559948/found-an-unexpected-mach-o-header-code-1918975009-in-xcode-6).

**Comment by FranciscoAmado** [comment]
@jtreanor I'm sorry to grind on this but I believe it isn't a setup problem.
I've checked the SO link you've generously said, worked around the various solutions and the error still persists.

I believe the problem is still on building the framework. The error no longer appears but when I do `carthage update` for Intercom the build is really fast. So, I've printed the **xcodebuild .log** and it is empty, yet, the **.framework** appears in Carthage/iOS

Once again, sorry to bother.

**Comment by jtreanor** [comment]
@FranciscoAmado No problem at all, I'm here to help.

The reason the xcodebuild log is empty and it is fast is that Carthage doesn't build `Intercom.framework` because it is already a prebuilt dynamic framework. That is the correct behaviour. I believe it should give you an error if the framework is valid (as it did previously).

The error you give seems to be an integration error of some kind in your Xcode project. Maybe you could try removing `Intercom.framework` from the project, checking that it builds and then re-adding it by dragging directly into `Embedded Binaries`?

**Comment by FranciscoAmado** [comment]
Hi @jtreanor, sorry for the delay.

Indeed, removing `Intercom` integration gave us the answer. The problem persists.
We believe it is caused due to another framework we are importing.

Thank you for all the help!
