### ISSUE TITLE
Getting lots of warning with latest version

### ISSUE THREAD

**Issue by allaire** [intercom/intercom-ios#97]
Warnings like:

```
(null): warning: Could not resolve external type c:objc(cs)NSMutableDictionary

warning: /var/folders/ln/xmg64wxx203243fp997n_ywc0000gn/C/org.llvm.clang.james/ModuleCache/3PDC6UWHV65FC/CoreFoundation-J9ZOXGK4ZTRR.pcm: No such file or directory
while processing /Users/allaire/Dropbox/Projects/agendrix/ios/Pods/Intercom/Intercom.framework/Intercom(FLAnimatedImage.o):```

**Comment by allaire** [comment]
Maybe related: http://stackoverflow.com/questions/14489692/what-do-these-dsymutil-warnings-mean-in-xcode-4-5

**Comment by jtreanor** [comment]
Hi @allaire,

Thanks for reporting this. Just a few questions to help track this down:

- Do you have Bitcode enabled?
- Is this happening for debug builds or archives? 
- Are you using CocoaPods?
- what version of Xcode are you using?

**Comment by allaire** [comment]
@jtreanor I'm on it, will report back in 5 mins :)

**Comment by allaire** [comment]
* Bitcode is disabled under "Build options" -> "Enable Bitcode"
* debug builds currently
* Using cocoapods
* Version 7.0 (7A220)

**Comment by allaire** [comment]
I had to disable Bitcode because of Google Analytics SDK: http://stackoverflow.com/questions/31395260/google-analytics-libadidaccess-a-does-not-contain-bitcode

**Comment by jtreanor** [comment]
Thanks for the quick response :smile: 

We are investigating this now.

**Comment by allaire** [comment]
Here's a screenshot of some the warnings:

![](https://dl.dropboxusercontent.com/s/bbdwi9y6rwr9jwj/2015-09-21%20at%2010.02.png)

It looks like something was weirdly compiled in the release build (we can see your name in the warnings :smile:)

**Comment by jtreanor** [comment]
Wow, that is very strange. I don't know where that could be coming from but I will continue to look into it here.

I have setup a new project as you describe (Xcode 7, CocoaPods, Bitcode disabled) and I am not seeing the warnings. Can you try running this project and see if you get the warnings?

Download it [here](http://d.pr/f/12gya)

**Comment by jtreanor** [comment]
@allaire I think I have found the issue. This is due to how [CocoaPods Packager](https://github.com/cocoapods/cocoapods-packager) handles builds with Bitcode (https://github.com/CocoaPods/cocoapods-packager/issues/98).

I'm working on a fix right now. I'll keep you updated.

**Comment by allaire** [comment]
@jtreanor great! for what's worth, your project gave me no Warnings. I tried on my side to remove the pod, and reinstall it, but no dice :)

**Comment by jtreanor** [comment]
@allaire Could you try change the line in your Podfile as shown below and let me know if it removes the warnings for you?

```
pod "Intercom", :git => "git@github.com:intercom/intercom-ios.git", :branch => "bitcode_fix"
```

**Comment by allaire** [comment]
I still get the warnings :disappointed:  I tried both `pod install` and `pod update`

**Comment by jtreanor** [comment]
Thanks @allaire 

I must say I am quite stumped here and I still haven't managed to reproduce it.

I am still investigating and will keep you updated.

**Comment by jtreanor** [comment]
I have made another change to the `bitcode_fix` branch. Could you run `pod update` and let me know if you still see issues?

**Comment by allaire** [comment]
Still seeing issues with latest changes :(

I wish I could send you the project I'm working on. Don't hesitate if you need any other information.

Thanks!

**Comment by jtreanor** [comment]
Thanks for checking @allaire 

I'll continue to look into it and keep you updated.

**Comment by allaire** [comment]
`pod "Intercom", "2.3.4"` fix it for now :)

**Comment by jtreanor** [comment]
I'm glad you have a temporary fix at least :smile:

**Comment by allaire** [comment]
@jtreanor Well, even with the latest version everything is working fine, but ignoring 200 warnings is pretty hard for me :laughing:

**Comment by gvalmon** [comment]
I'm experiencing the same issue

1) Bitcode is enabled
2) Both debu and archive builder
3) Using cocoapods
4) Xcode Version 7.0
5) Project written using Swift, but has 1 file with Objective-C code

**Comment by jtreanor** [comment]
Thanks @gvalmon 

Another temporary workaround is to silence the warnings like this:

```
pod 'Intercom', :inhibit_warnings => true
```

**Comment by flipdish** [comment]
2.3.5 broke my build. Getting error 
 
    /Users/distiller/ios/Pods/Intercom/Intercom.framework/Intercom(SocketRocket-dummy.o)
    ld: 362 duplicate symbols for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)-

Swift project targeting iOS 7

**Comment by jtreanor** [comment]
@flipdish This is likely unrelated to this issue. Are you using Xcode 6.x? [This issue](https://github.com/intercom/intercom-ios/issues/98) may be of interest to you.

**Comment by flipdish** [comment]
@jtreanor Thanks - yes, https://github.com/intercom/intercom-ios/issues/98 looks like the issue.  We're using XCode 6.4.

**Comment by afehners** [comment]
I am seeing the same issue

Bitcode disabled
Xcode 7
using cocoapods
debug & archive builds
All Objective C project

**Comment by jtreanor** [comment]
I have released 2.3.6 which I am very hopeful will fix this. Let me know how it goes :smile:

**Comment by allaire** [comment]
Driving to work will report in 15min. What did you change?

**Comment by jtreanor** [comment]
Thanks @allaire.

I have changed how CocoaPods packager mangles symbols so Xcode shouldn't get confused and need to check the ModuleCache.

**Comment by afehners** [comment]
2.3.6 is causing a build error now sorry

I think the issue is due to me using AFNetworking. I get error due to duplicate symbols now.

![screen_shot_2015-09-22_at_13_23_47](https://cloud.githubusercontent.com/assets/2273006/10018290/7021d1a4-612d-11e5-99e2-7d9928e26e50.png)

**Comment by jtreanor** [comment]
Thanks @afehners.

We're clearly still not out of the woods :disappointed: I'm on it.

**Comment by allaire** [comment]
@jtreanor Not working for me neither! Also, `inhibit_warnings` does not work (might be an issue with cocoapods itself?)

**Comment by jtreanor** [comment]
Thanks @allaire.

I have found the issue and I'm in the process of cutting a new version now.

Thanks everyone for all your patience.

**Comment by allaire** [comment]
Great! just wondering, is inhibit_warnings working on your side with latest cocoapods beta?

**Comment by jtreanor** [comment]
2.3.7 is released and should fix this issue.

@allaire I'll check now :smile:

**Comment by jtreanor** [comment]
@allaire `inhibit_warnings` works for me! (Not with Intercom 2.3.6 though since those as errors)

**Comment by allaire** [comment]
@jtreanor Ran `pod update`, tried to clean + delete DerivedData and still getting warnings, anything else?

**Comment by afehners** [comment]
Sorry but back to the original warnings again now...

**Comment by jtreanor** [comment]
Thanks guys.

**Comment by jtreanor** [comment]
We have finally been able to reproduce this locally.

The warnings are given when "Debug Information Format" is set to "DWARF with dSYM File". We don't have a fix quite yet but setting it to "DWARF" will fix it for now.

**Comment by allaire** [comment]
@jtreanor Great. Do you know the difference between the two settings? Could not fit anything meaningful  on the Interwebs!

**Comment by allaire** [comment]
I think that Crashlytics makes use of the dSYM file and enable it when you install Fabric/Crashlytics in your app.

**Comment by jtreanor** [comment]
@allaire Yes it does. That what it is primarily used for. I'm confident we'll get to the bottom of this for all use cases.

**Comment by tecknut** [comment]
@jtreanor if don't use the @import statement in your codebase you should set CLANG_ENABLE_MODULES. This resolves this issue, and should allow the use of DWARF with dSYM File.

**Comment by jtreanor** [comment]
Thanks @tecknut, I'll try that.

**Comment by jtreanor** [comment]
This has been fixed in 2.3.8. Thanks everyone for your patience.

There is an issue in Xcode that we have worked around [here](https://github.com/CocoaPods/cocoapods-packager/issues/101).

**Comment by allaire** [comment]
@jtreanor Yay great working hunting this down. Apple probably made DWARF in debug by default because it's much faster to build without it (https://labs.spotify.com/2013/11/04/shaving-off-time-from-the-ios-edit-build-test-cycle/)
